"""Initial schema

Revision ID: 31a3e57cdd5d
Revises:
Create Date: 2025-11-22 15:57:13.864269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31a3e57cdd5d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "screenshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("image_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("required_annotations", sa.Integer(), nullable=False),
        sa.Column("current_annotation_count", sa.Integer(), nullable=False),
        sa.Column("has_consensus", sa.Boolean(), nullable=True),
        sa.Column(
            "uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_status", sa.String(length=50), nullable=False),
        sa.Column("extracted_title", sa.String(length=500), nullable=True),
        sa.Column("extracted_total", sa.String(length=100), nullable=True),
        sa.Column("extracted_hourly_data", sa.JSON(), nullable=True),
        sa.Column("title_y_position", sa.Integer(), nullable=True),
        sa.Column("grid_upper_left_x", sa.Integer(), nullable=True),
        sa.Column("grid_upper_left_y", sa.Integer(), nullable=True),
        sa.Column("grid_lower_right_x", sa.Integer(), nullable=True),
        sa.Column("grid_lower_right_y", sa.Integer(), nullable=True),
        sa.Column("processing_issues", sa.JSON(), nullable=True),
        sa.Column("has_blocking_issues", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_index(op.f("ix_screenshots_id"), "screenshots", ["id"], unique=False)
    op.create_index(op.f("ix_screenshots_processing_status"), "screenshots", ["processing_status"], unique=False)
    op.create_index(op.f("ix_screenshots_status"), "screenshots", ["status"], unique=False)
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("screenshot_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hourly_values", sa.JSON(), nullable=False),
        sa.Column("extracted_title", sa.String(length=500), nullable=True),
        sa.Column("extracted_total", sa.String(length=100), nullable=True),
        sa.Column("grid_upper_left", sa.JSON(), nullable=True),
        sa.Column("grid_lower_right", sa.JSON(), nullable=True),
        sa.Column("time_spent_seconds", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["screenshot_id"], ["screenshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annotations_id"), "annotations", ["id"], unique=False)
    op.create_index(op.f("ix_annotations_screenshot_id"), "annotations", ["screenshot_id"], unique=False)
    op.create_index(op.f("ix_annotations_status"), "annotations", ["status"], unique=False)
    op.create_index(op.f("ix_annotations_user_id"), "annotations", ["user_id"], unique=False)
    op.create_table(
        "consensus_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("screenshot_id", sa.Integer(), nullable=False),
        sa.Column("has_consensus", sa.Boolean(), nullable=False),
        sa.Column("disagreement_details", sa.JSON(), nullable=False),
        sa.Column("consensus_values", sa.JSON(), nullable=True),
        sa.Column(
            "calculated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["screenshot_id"], ["screenshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consensus_results_id"), "consensus_results", ["id"], unique=False)
    op.create_index(op.f("ix_consensus_results_screenshot_id"), "consensus_results", ["screenshot_id"], unique=True)
    op.create_table(
        "user_queue_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("screenshot_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "last_accessed", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["screenshot_id"], ["screenshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_queue_states_id"), "user_queue_states", ["id"], unique=False)
    op.create_index(op.f("ix_user_queue_states_screenshot_id"), "user_queue_states", ["screenshot_id"], unique=False)
    op.create_index(op.f("ix_user_queue_states_status"), "user_queue_states", ["status"], unique=False)
    op.create_index(op.f("ix_user_queue_states_user_id"), "user_queue_states", ["user_id"], unique=False)
    op.create_table(
        "processing_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("annotation_id", sa.Integer(), nullable=False),
        sa.Column("issue_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["annotation_id"], ["annotations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_issues_annotation_id"), "processing_issues", ["annotation_id"], unique=False)
    op.create_index(op.f("ix_processing_issues_id"), "processing_issues", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_issues_id"), table_name="processing_issues")
    op.drop_index(op.f("ix_processing_issues_annotation_id"), table_name="processing_issues")
    op.drop_table("processing_issues")
    op.drop_index(op.f("ix_user_queue_states_user_id"), table_name="user_queue_states")
    op.drop_index(op.f("ix_user_queue_states_status"), table_name="user_queue_states")
    op.drop_index(op.f("ix_user_queue_states_screenshot_id"), table_name="user_queue_states")
    op.drop_index(op.f("ix_user_queue_states_id"), table_name="user_queue_states")
    op.drop_table("user_queue_states")
    op.drop_index(op.f("ix_consensus_results_screenshot_id"), table_name="consensus_results")
    op.drop_index(op.f("ix_consensus_results_id"), table_name="consensus_results")
    op.drop_table("consensus_results")
    op.drop_index(op.f("ix_annotations_user_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_status"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_screenshot_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_id"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_index(op.f("ix_screenshots_status"), table_name="screenshots")
    op.drop_index(op.f("ix_screenshots_processing_status"), table_name="screenshots")
    op.drop_index(op.f("ix_screenshots_id"), table_name="screenshots")
    op.drop_table("screenshots")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
