"""Add missing columns: annotation_status, group_id, participant_id, etc

Revision ID: 3613c2977638
Revises: i7j8k9l0m1n2
Create Date: 2026-02-24 00:45:40.453885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3613c2977638'
down_revision: Union[str, None] = 'i7j8k9l0m1n2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create groups table BEFORE adding FK from screenshots.group_id → groups.id
    op.create_table(
        'groups',
        sa.Column('id', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('image_type', sa.String(length=50), nullable=False, server_default='screen_time'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.drop_index(op.f('ix_preprocessing_jobs_status'), table_name='preprocessing_jobs')
    op.drop_index(op.f('ix_preprocessing_jobs_user_id'), table_name='preprocessing_jobs')
    op.drop_index(op.f('ix_preprocessing_jobs_user_status'), table_name='preprocessing_jobs')
    op.drop_table('preprocessing_jobs')
    op.drop_index(op.f('ix_annotations_created_at'), table_name='annotations')
    op.add_column('screenshots', sa.Column('annotation_status', sa.Enum('PENDING', 'ANNOTATED', 'VERIFIED', 'SKIPPED', name='annotationstatus', native_enum=False), nullable=False))
    op.add_column('screenshots', sa.Column('participant_id', sa.String(length=100), nullable=True))
    op.add_column('screenshots', sa.Column('group_id', sa.String(length=100), nullable=True))
    op.add_column('screenshots', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('screenshots', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('screenshots', sa.Column('screenshot_date', sa.Date(), nullable=True))
    op.add_column('screenshots', sa.Column('alignment_score', sa.Float(), nullable=True))
    op.add_column('screenshots', sa.Column('verified_by_user_ids', sa.JSON(), nullable=True))
    op.alter_column('screenshots', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED', 'DELETED', name='processingstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('screenshots', 'processing_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OCR_ANCHORED', 'LINE_BASED', 'MANUAL', name='processingmethod', native_enum=False),
               existing_nullable=True)
    op.drop_index(op.f('ix_screenshots_status'), table_name='screenshots')
    op.create_index(op.f('ix_screenshots_annotation_status'), 'screenshots', ['annotation_status'], unique=False)
    op.create_index('ix_screenshots_group_date', 'screenshots', ['group_id', 'screenshot_date'], unique=False)
    op.create_index(op.f('ix_screenshots_group_id'), 'screenshots', ['group_id'], unique=False)
    op.create_index('ix_screenshots_group_id_asc', 'screenshots', ['group_id', 'id'], unique=False)
    op.create_index('ix_screenshots_group_processing', 'screenshots', ['group_id', 'processing_status'], unique=False)
    op.create_index(op.f('ix_screenshots_participant_id'), 'screenshots', ['participant_id'], unique=False)
    op.create_index(op.f('ix_screenshots_screenshot_date'), 'screenshots', ['screenshot_date'], unique=False)
    op.create_foreign_key('screenshots_group_id_fkey', 'screenshots', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.drop_column('screenshots', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, server_default='pending'))
    # Remove the server_default after backfilling
    op.alter_column('screenshots', 'status', server_default=None)
    # Drop FK to groups (created with no explicit name — PostgreSQL auto-names it)
    op.drop_constraint('screenshots_group_id_fkey', 'screenshots', type_='foreignkey')
    op.drop_index(op.f('ix_screenshots_screenshot_date'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_participant_id'), table_name='screenshots')
    op.drop_index('ix_screenshots_group_processing', table_name='screenshots')
    op.drop_index('ix_screenshots_group_id_asc', table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_group_id'), table_name='screenshots')
    op.drop_index('ix_screenshots_group_date', table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_annotation_status'), table_name='screenshots')
    op.create_index(op.f('ix_screenshots_status'), 'screenshots', ['status'], unique=False)
    op.alter_column('screenshots', 'processing_method',
               existing_type=sa.Enum('OCR_ANCHORED', 'LINE_BASED', 'MANUAL', name='processingmethod', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('screenshots', 'processing_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED', 'DELETED', name='processingstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('screenshots', 'verified_by_user_ids')
    op.drop_column('screenshots', 'alignment_score')
    op.drop_column('screenshots', 'screenshot_date')
    op.drop_column('screenshots', 'device_type')
    op.drop_column('screenshots', 'source_id')
    op.drop_column('screenshots', 'group_id')
    op.drop_column('screenshots', 'participant_id')
    op.drop_column('screenshots', 'annotation_status')
    op.create_index(op.f('ix_annotations_created_at'), 'annotations', ['created_at'], unique=False)
    op.create_table('preprocessing_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processed_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('redaction_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detection_preset', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('zip_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('extracted_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uploaded_screenshot_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('phi_stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('preprocessing_jobs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('preprocessing_jobs_pkey'))
    )
    op.create_index(op.f('ix_preprocessing_jobs_user_status'), 'preprocessing_jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_preprocessing_jobs_user_id'), 'preprocessing_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_preprocessing_jobs_status'), 'preprocessing_jobs', ['status'], unique=False)

    # Drop groups table (created in upgrade)
    op.drop_table('groups')
    # ### end Alembic commands ###
